config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :products do
    resources :comments
  end

  root "products#index"

  get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_attached_file :image, styles: {large: "600x600>", medium: "300x300>", thumb: "150x150#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@product = Product.find(params[:product_id])
		@comment = @product.comments.create(params[:comment].permit(:name, :body))

		redirect_to product_path(@product)
	end

	def destroy
		@product = Product.find(params[:product_id])
		@comment = @product.comments.find(params[:id])
		@comment.destroy

		redirect_to product_path(@product)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@products = Product.all.order('created_at DESC').paginate(page: params[:page], per_page: 10)
	end

	def new
		@product=Product.new
	end

	def create
		@product=Product.new(product_params)
		
		if @product.save
			redirect_to @product
		else
			render 'new'
		end
	end

	def show
		@product = Product.find(params[:id])
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])

		if @product.update(params[:product].permit(:title, :body, :image))
			redirect_to @product
		else
			render 'edit'
		end	
	end

	def destroy
		@product = Product.find(params[:id])
		@product.destroy

		redirect_to root_path
	end

	private
		def product_params
			params.require(:product).permit(:title, :body, :image)
		end	 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>
	<% if user_signed_in? %>
		<p><%= link_to 'Delete', [comment.product, comment],
						method: :delete,
						class: "button",
						data: { confirm: "Are you sure?" } %>
		</p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@product, @product.comments.build]) do |f| %>
	<p>
		<%= f.label :name %><br>
		<%= f.text_field :name %><br>
	</p>
	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %><br>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="sidebar">
		<div id="logo">
			<%= link_to root_path do %>
				<% image_tag "logo.png" %>
			<% end %>
		</div>

		<ul>
			<li class="Category">Website</li>
			<li><%= link_to "Ecommerce", root_path %></li>
			<li><%= link_to "About", about_path %></li>
		</ul>

		<% if !user_signed_in? %>
			<p class="sign_in"><%= link_to "Admin Login", new_user_session_path %></p>
		<% end %>
	</div>
	<div id="main_content">
		<div id="header">
			<% if current_page?(root_path) %>
				<p>All Products</p>
			<% elsif current_page?(about_path) %>
				<p>About</p>
			<% else %>
				<%= link_to "Back to All Products", root_path %>
			<% end %>
			<% if user_signed_in? %>
				<div class="buttons">
					<%= link_to "New Product", new_product_path, :class => "button" %>
					<%= link_to "Log Out", destroy_user_session_path, :class => "button", method: :delete %>
				</div>
			<% end %>
		</div>

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "profile.jpg" %>
	</div>

	<div id="content">
		<h1>Hey, I'm Abhishek Dutta</h1>
		<p>Welcome to our Ecommerce Website</p>
		<p>This week I built a ecommerce store in Rails 4. Cool stuff, right!.</p>
		<p>If you'd like to follow along as I learn more Ruby on Rails, find me on Twitter or on the web, and get my posts and exclusive content in your inbox by signing up for my newsletter 
		</p>
	</div>
</div>

app/views/products/_form.html.erb
<%= form_for @product, html: {multipart: true} do |f| %>
		<% if @product.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@product.errors.count, "error") %> prevented this product from saving</h2>
				<ul>
					<% @product.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<p>
			<%= f.label :image %><br>
			<%= f.file_field :image %>
		</p>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :body %><br>
			<%= f.text_area :body %>
		</p>
		<p>
			<%= f.submit %>
		</p>
	<% end %>

app/views/products/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Product</h1>

	<%= render 'form' %>
</div>

app/views/products/index.html.erb
<% @products.each do |product| %>
	<div class="col-lg-3 col-sm-6">
		<div class="product_wrapper">
			<h5 class="title"><%= link_to product.title, product %></h5>
			<p class="date"><%= product.created_at.strftime("%B, %d, %Y") %></p>
			<p><%= image_tag product.image.url(:thumb) %></p>
		</div>
	</div>
<% end %>

<%= will_paginate @products, renderer: BootstrapPagination::Rails %>

app/views/products/new.html.erb
<div id="page_wrapper">
	<h1>New Product</h1>

	<%= render 'form' %>
</div>

app/views/products/show.html.erb
<div id="product_content">
	<h1 class="title">
		<%= @product.title %>
	</h1>
	<p class="date">
		Submitted <%= time_ago_in_words(@product.created_at) %> Ago
		<% if user_signed_in? %>
		| <%=link_to 'Edit', edit_product_path(@product) %> |
		  <%= link_to 'Delete', product_path(@product), method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</p>

		<%= image_tag @product.image.url{:medium} %>
	
	<p class="body">
		<%= @product.body %>
	</p>

	<div id="comments">
		<h2><%= @product.comments.count %> Comments</h2>
		<%= render @product.comments %>

		<h3>Add a comment:</h3>
		<%= render "comments/form" %>
	</div>
</div>